version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "yarn dev"
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      PORT: ${PORT}
