version: '3'

services:
  pokemon-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "yarn dev"
    ports:
      - "${PORT}:${PORT}"
    # Load environment variables from the specified file
    env_file: .env
    # Set the PORT environment variable for the application
    environment:
      PORT: ${PORT}
    # Mount the current directory to the docker container /app
    volumes:
      - .:/app
    depends_on:
      - pokemon-db

  pokemon-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
  
  # Database Initialization Container
  init-db:
    build:
      context: .
      dockerfile: Dockerfile
      target: dbinit
    volumes:
      - ./scripts/init-db.sh:/app/init-db.sh
      - ./scripts/init-db.sql:/app/init-db.sql
    depends_on:
      - pokemon-db
  
  redis-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
    volumes:
      - redis-data:/data

volumes:
  redis-data: