version: '3'

services:
  pokemon-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "yarn dev"
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      PORT: ${PORT}

  pokemon-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: always
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"