version: '3'

services:
  pokemon-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: bash -c "yarn dev"
    ports:
      - "${PORT}:${PORT}"
    # Load environment variables from the specified file
    env_file: .env
    # Set the PORT environment variable for the application
    environment:
      PORT: ${PORT}
    # Mount the current directory to the docker container /app
    volumes:
      - .:/app
    depends_on:
      - pokemon-db

  pokemon-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: always
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"